# Generated by Django 3.1.4 on 2021-01-05 00:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WorkReporting', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('date', models.DateField(default=datetime.date.today)),
                ('hours', models.DecimalField(decimal_places=2, max_digits=6)),
                ('employee_email', models.EmailField(max_length=70)),
            ],
            options={
                'db_table': 'task',
                'ordering': ['id'],
            },
        ),
        migrations.DeleteModel(
            name='Employee',
        ),
    ]
