# Generated by Django 3.1.4 on 2021-01-05 00:28

from django.db import migrations

def create_dummy_tasks(apps, schema_editor):
    task = apps.get_model('WorkReporting', 'task')

    task(title='Meeting', hours=2, employee_email='useremail@gmail.com').save()
    task(title='Designing', hours=6, employee_email='useremail@gmail.com').save()


class Migration(migrations.Migration):

    dependencies = [
        ('WorkReporting', '0002_auto_20210105_0026'),
    ]

    operations = [
        migrations.RunPython(create_dummy_tasks),
    ]
