# Generated by Django 3.1.4 on 2021-01-21 20:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WorkReporting', '0003_mock_tasks'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Task',
        ),
    ]
