# Generated by Django 3.1.4 on 2021-01-21 23:31

from django.db import migrations
from django.contrib.auth.models import User, Permission

def create_admin(apps, schema_editor):
    user = User.objects.create_user('admin', 'admin@gmail.com', 'Model*121!')
    user.is_admin = True
    user.save()

class Migration(migrations.Migration):

    dependencies = [
        ('WorkReporting', '0005_task'),
    ]

    operations = [
        migrations.RunPython(create_admin),
    ]
