# Generated by Django 3.1.4 on 2021-01-22 00:02

from django.db import migrations
from django.contrib.auth.models import User, Permission

def create_admin(apps, schema_editor):
    user = User.objects.create_user('admin1', 'admin1@gmail.com', 'Model*121!')
    user.is_staff = True
    user.save()

class Migration(migrations.Migration):

    dependencies = [
        ('WorkReporting', '0006_AddAdmin'),
    ]

    operations = [
        migrations.RunPython(create_admin),
    ]
